### ISSUE TITLE
Redis is not a module

### ISSUE THREAD

**Issue by n-rodriguez** [redis-store/redis-rack-cache#15]
Got this error when requiring ```redis-rack-cache``` : ```Redis is not a module``` :
```
Gem Load Error is: Redis is not a module
Backtrace for gem load error is:
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/redis-rack-cache-0.0.0/lib/redis-rack-cache/version.rb:1:in `<top (required)>'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/redis-rack-cache-0.0.0/lib/redis-rack-cache.rb:1:in `<top (required)>'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/nicolas/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
```

**Comment by tubbo** [comment]
@n-rodriguez you seem to be using a very old version of redis-rack-cache. bundler sometimes does this when it has trouble finding a particular version that matches up with rails. can you try using the following syntax in your Gemfile?

```ruby
gem 'redis-rack-cache', '2.0.0.pre'
```

**Comment by n-rodriguez** [comment]
It works. Thanks!
