### ISSUE TITLE
Unknown storage provider

### ISSUE THREAD

**Issue by jfloff** [redis-store/redis-rack-cache#32]
Hello there,

I'm trying to configure this gem, but I'm getting some errors. 

Currently, this is my configuration (similar to the one found in the README):

```
config.action_dispatch.rack_cache = {
    metastore: ::Rack::Cache::MetaStore::Redis.new("#{ENV['REDIS_URL']}/1/metastore"),
    entitystore: ::Rack::Cache::EntityStore::Redis.new("#{ENV['REDIS_URL']}/1/entitystore")
}
```

But I'm getting this error:
```
cache error: Unknown storage provider: #<Rack::Cache::MetaStore::Redis:0x0000557d22a306e8>
/app/vendor/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/storage.rb:52:in `create_store'
/app/vendor/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/storage.rb:18:in `resolve_metastore_uri'
/app/vendor/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:35:in `metastore'
/app/vendor/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:176:in `lookup'
/app/vendor/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:67:in `call!'
/app/vendor/bundle/ruby/2.7.0/gems/rack-cache-1.13.0/lib/rack/cache/context.rb:52:in `call'
```

These are my gem versions:
    rack-cache (1.13.0)
    redis-rack-cache (2.2.1)

**Comment by tubbo** [comment]
`Rack::Cache::MetaStore::Redis.new` instantiates a client which is not the same thing as supplying the URL. The correct way of specifying your Redis stores are as follows:

```ruby
config.action_dispatch.rack_cache = {
    metastore: "#{ENV['REDIS_URL']}/1/metastore",
    entitystore: "#{ENV['REDIS_URL']}/1/entitystore",
}
```
